### ISSUE TITLE
trusty

### ISSUE THREAD

**Issue by Megamouse** [hcorion/rpcs3-docker#2]
The min version of Qt has been set to 5.11.0 In the main project.
This isn't reflected in the trusty dockerfile.

Apart from that I think that file can be deleted anyway ?

**Comment by hcorion** [comment]
Yeah, since our provider of Qt: https://launchpad.net/~beineri doesn't have support for Qt versions 5.11.0 and greater on Trusty, there's no point in doing anything else with the trusty build script. I'll delete the old build script at some point.
